---
title: "Infant int"
author: "David Amadi"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    social: menu
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(shiny)
#library(shinydashboard)
#library(purrr)
#source("override.R", local = TRUE) # override 'icon' and 'valueBox'

```



```{r, echo=FALSE, message=FALSE}
#upload data change location
infants <- read.csv("/Users/damadi/Desktop/samp_data/imun.csv")
infants <-as.data.frame(infants)

coverage <-table(infants$immun)
coverage <-as.data.frame(coverage)

data <- coverage[,c('Var1', 'Freq')]

p <- plot_ly(data, labels = ~Var1, values = ~Freq, type = 'pie',textinfo = 'label+percent') %>%
  layout(title = 'Immunisation Proportion',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

print(p)

###Guage anc attendance

anc <-as.data.frame(table(infants$anc_attended))




anc<-infants %>%
  group_by (anc_attended) %>%
  summarise (n=n()) %>%
  mutate(freq = paste0(round(100 * n/sum(n), 0), "%"))

anc$anc_attended <- factor(anc$anc_attended, levels = c(0,1,6,99),
labels = c("Not Attending", "Attending","Error", "Dont Know"))




```

```{r}


  
  
```


Row
-----------------------------------------------------------------------

### Participants

```{r}
output$articles <- renderValueBox({
  pop <- as.data.frame(infants)
valueBox(
     paste0(nrow(pop)),
     icon = "fa-comments",
    color = "olive")
})

valueBoxOutput("articles")

```

### Immunisation Coverage

```{r}
df <-as.data.frame(infants)
missing.age <- is.na(df$mum_age)
df <- df[!missing.age,]  # select only those not missing ages
labs <- c(paste(seq(0, 95, by = 5), seq(0 + 5 - 1, 100 - 1, by = 5),
                sep = "-"), paste(100, "+", sep = ""))
labs

df$AgeGroup <- cut(df$mum_age, breaks = c(seq(0, 100, by = 5), Inf), labels = labs, right = FALSE)
head(df[c("mum_age", "AgeGroup")], 15)

#collapse
df1 <-table(df$AgeGroup)
df1 <-as.data.frame(df1)

agegroups <-as.data.frame(filter(df1, Freq >0))


p <- plot_ly(agegroups, x = ~Var1, y = ~Freq, type = 'bar', name = 'SF Zoo') %>%
  layout(yaxis = list(title = 'Count'), barmode = 'group')

print(p)

  
  
 


```


### ANC Coverage

```{r}

    
   gauge(anc$freq[2], min = 0, max = 100, gaugeSectors(
  success = c(80, 100), warning = c(40, 79), danger = c(0, 39)
))


```

### Immunisation Proportion:

```{r}




plot_ly(data, labels = ~Var1, values = ~Freq, type = 'pie',textinfo = 'label+percent') %>%
  layout(title = '',
         xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
         yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))








```


